### ISSUE TITLE
Add object folders to gitignore.

### ISSUE THREAD

**Issue by minerscale** [fido2020/Lemon-OS-old#1]
Don't track build files, it increases the time git takes to clone by a lot. Git doesn't handle binary files well.

PS if you're on discord PM me @Minerscale#9319

PPS I'm that kid in yr 10 who thought your project is cool

**Comment by fido2020** [comment]
thanks, done. Discord tag didnt work though

**Comment by minerscale** [comment]
Gimme yours then, I'll PM ya :D

**Comment by fido2020** [comment]
@ComputerFido#5783

**Comment by minerscale** [comment]
Didn't worked???
